version: 2.1

orbs:
  orb-tools: circleci/orb-tools@3.0.0
  aws-cli: circleci/aws-cli@0.1.8
  aws-ecr: circleci/aws-ecr@dev:alpha
  circle-compare-url: iynere/compare-url@0.4.5

executors:
  ci-base:
    resource_class: small
    docker:
      - image: cibuilds/base

  cli:
    resource_class: small
    docker:
      - image: circleci/circleci-cli

  lint-condo:
    resource_class: small
    docker:
      - image: singapore/lint-condo

jobs:
  lint:
    executor: lint-condo
    steps:
      - checkout
      - run: yamllint .

workflows:
  lint-pack_validate_deploy-dev:
    jobs:
      - lint

      - orb-tools/pack:
          name: pack-go-module
          source-dir: src/go-module
          destination-orb-path: packed/go-module-orb.yml
          workspace-path: packed/go-module-orb.yml
          artifact-path: packed/go-module-orb.yml
          requires:
            - lint

      - orb-tools/pack:
          name: pack-reviewdog
          source-dir: src/reviewdog
          destination-orb-path: packed/reviewdog-orb.yml
          workspace-path: packed/reviewdog-orb.yml
          artifact-path: packed/reviewdog-orb.yml
          requires:
            - lint
