version: 2.1

executors:
  cli:
    docker:
      - image: circleci/circleci-cli:latest
  python:
    docker:
      - image: python:3.7.0-alpine3.8

commands:
  validate_orb:
    steps:
      - run:
          name: Validate orb yaml files
          command: |
            ORB_FILES=$(circleci tests glob "src/**/*.yml" | circleci tests split)
            for f in $ORB_FILES;
            do
              echo "Validating $f ..."
              circleci orb validate $f
            done
  install_yamllint:
    steps:
      - run:
          name: Install yamllint
          command: |
            pip3 install -U -v yamllint
  run_yamllint:
    steps:
      - run:
          name: Run yamllint
          command: |
            yamllint .
  publish:
    steps:
      - run:
          name: Publish Orbs
          command: |
            make publish

jobs:
  validate:
    executor: cli
    parallelism: 4
    steps:
      - checkout
      - validate_orb
  lint:
    executor: python
    steps:
      - checkout
      - install_yamllint
      - run_yamllint
  publish:
    executor: cli
    steps:
      - checkout
      - publish
workflows:
  version: 2
  main:
    jobs:
      - validate:
          context: org-global
      - lint:
          context: org-global
      - publish:
          context: org-global
          requires:
            - validate
            - lint
          filters:
            branches:
              only: master