version: 2.1

orbs:
  orb-tools: circleci/orb-tools@7.0.0
  aws-cli: circleci/aws-cli@0.1.8
  aws-ecr: circleci/aws-ecr@dev:alpha
  circle-compare-url: iynere/compare-url@0.4.5

executors:
  ci-base:
    resource_class: small
    docker:
      - image: cibuilds/base

  cli:
    resource_class: small
    docker:
      - image: circleci/circleci-cli

jobs:
  publish-dev:
    executor: cli
    steps:
      - checkout

      - attach_workspace:
          at: workspace

      - run:
          name: publish dev versions
          command: |
            # for integration testing
            circleci orb publish workspace/packed/reviewdog-orb.yml timakin/reviewdog@dev:alpha --token $CIRCLE_TOKEN
            circleci orb publish workspace/packed/go-module-orb.yml timakin/go-module@dev:alpha --token $CIRCLE_TOKEN
            # for transparency
            circleci orb publish workspace/packed/reviewdog-orb.yml timakin/reviewdog@dev:$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN
            circleci orb publish workspace/packed/go-module-orb.yml timakin/go-module@dev:$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN
            # for potentially promoting to prod
            circleci orb publish workspace/packed/reviewdog-orb.yml timakin/reviewdog@dev:${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN
            circleci orb publish workspace/packed/go-module-orb.yml timakin/go-module@dev:${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN

      - store_artifacts:
          path: workspace/reviewdog-orb.yml
      - store_artifacts:
          path: workspace/go-module-orb.yml

workflows:
  lint-pack_validate_deploy-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          name: pack-go-module
          source-dir: src/go-module
          destination-orb-path: packed/go-module-orb.yml
          workspace-path: packed/go-module-orb.yml
          artifact-path: packed/go-module-orb.yml
          requires:
            - orb-tools/lint

      - orb-tools/pack:
          name: pack-reviewdog
          source-dir: src/reviewdog
          destination-orb-path: packed/reviewdog-orb.yml
          workspace-path: packed/reviewdog-orb.yml
          artifact-path: packed/reviewdog-orb.yml
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          context: orb-publishing
          orb-name: timakin/reviewdog
          orb-path: workspace/packed/reviewdog-orb.yml
          requires:
            - pack-reviewdog

      - orb-tools/publish-dev:
          context: orb-publishing
          orb-name: timakin/go-module
          orb-path: workspace/packed/go-module-orb.yml
          requires:
            - pack-go-module
