version: 2.1

orbs:
  orb-tools: circleci/orb-tools@7.0.0

workflows:
  lint-pack_validate_deploy-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          name: pack-go-module
          source-dir: src/go-module
          destination-orb-path: packed/go-module-orb.yml
          workspace-path: packed/go-module-orb.yml
          artifact-path: packed/go-module-orb.yml
          requires:
            - orb-tools/lint

      - orb-tools/pack:
          name: pack-reviewdog
          source-dir: src/reviewdog
          destination-orb-path: packed/reviewdog-orb.yml
          workspace-path: packed/reviewdog-orb.yml
          artifact-path: packed/reviewdog-orb.yml
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          name: publish-dev-go-module
          context: orb-publishing
          orb-name: timakin/reviewdog
          orb-path: workspace/packed/reviewdog-orb.yml
          requires:
            - pack-reviewdog

      - orb-tools/publish-dev:
          name: publish-dev-go-module
          context: orb-publishing
          orb-name: timakin/go-module
          orb-path: workspace/packed/go-module-orb.yml
          requires:
            - pack-go-module
